name: decompositions
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.9.0
  - aiosignal=1.3.1
  - anyio=4.2.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=11.0.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2023.12.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - dataclasses=0.8
  - datasets=2.16.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - grpc-cpp=1.48.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - huggingface_hub=0.20.2
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.29.2
  - ipython=8.21.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.1
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.1.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - nb_conda_kernels=2.3.1
  - nbclient=0.8.0
  - nbconvert-core=7.16.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nltk=3.8.1
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.3.0
  - openssl=3.2.1
  - orc=1.7.4
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.21
  - pygments=2.17.2
  - pyobjc-core=9.0
  - pyobjc-framework-cocoa=9.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.4
  - python-xxhash=2.0.2
  - pytorch=2.2.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.33.0
  - regex=2023.10.3
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - sacremoses=0.0.53
  - safetensors=0.4.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - send2trash=1.8.2
  - sentence-transformers=2.3.1
  - sentencepiece=0.1.99
  - setuptools=69.0.3
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenizers=0.13.2
  - tomli=2.0.1
  - torchaudio=2.2.0
  - torchvision=0.17.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.1
  - transformers=4.31.0
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - xxhash=0.8.0
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - contourpy==1.2.0
    - cycler==0.12.1
    - dataclasses-json==0.5.14
    - fonttools==4.48.1
    - jsonlines==4.0.0
    - kiwisolver==1.4.5
    - langchain==0.0.186
    - marshmallow==3.20.2
    - matplotlib==3.8.2
    - mypy-extensions==1.0.0
    - openai==0.28.0
    - openapi-schema-pydantic==1.2.4
    - pydantic==1.10.14
    - pyparsing==3.1.1
    - simple-colors==0.1.5
    - sqlalchemy==2.0.25
    - tenacity==8.2.3
    - typing-inspect==0.9.0